version: '2'

services:
  app:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"

  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    volumes_from:
      - app
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.6
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=dockerlaravel"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
    ports:
      - "3306:3306"
